### ISSUE TITLE
SyntaxError during installation

### ISSUE THREAD

**Issue by appscluster** [mklymyshyn/arango-python#9] opened 2014-04-12 19:41 UTC
Hi,
During installation on Ubuntu 12.04.4 64bit and using python 2.7.3

The following error is reported:
Installing collected packages: arango
  Running setup.py install for arango

```
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/arango/async.py', 12, 29, '    return CommandsProxy(obj\n'))
```

Successfully installed arango
Cleaning up...

When trying to run the default script the following error is reported:
AttributeError: 'module' object has no attribute 'create'

I can only assume the installation has failed. Can you please help?

Thanks

**Comment by appscluster** [comment] 2014-04-12 19:46
Managed to fix the installation problem by removing /usr/local/man
However, unable to import create from arango error is still reported.

**Comment by fceller** [comment] 2014-04-15 10:09
Is this a duplicate of #10?

**Comment by appscluster** [comment] 2014-04-15 10:24
It was throwing a different error which I managed to fix on my end. It is a duplicate of #10. Which I have closed.

**Comment by fceller** [comment] 2014-04-15 10:56
I'm trying to reproduce the error. I have setup a Ubuntu 12.10. I hope that does not make to much difference.

```
> git clone https://github.com/joymax/arango-python.git
> cd arango-python/
> python --version
Python 2.7.3
> sudo python setup.py install
```

That all did not produce an error. 

```
> python 
Python 2.7.3 (default, Feb 27 2014, 19:37:34) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from arango import create
>>> create
<function create at 0x23031b8>
```

So, I'm a bit lost. How do I trigger the error? Is there a big difference between Ubuntu 12.04 and 12.10?

**Comment by appscluster** [comment] 2014-04-15 11:34
There maybe a difference on quick observation I used the pip tool "pip install arango" which appears to have this async.py file. When grabbing the repository zip file this async.py isn't there.

Went through the following steps:
pip uninstall arango
wget https://github.com/joymax/arango-python/archive/master.zip
7za x master.zip
cd arango-python-master/
sudo python setup.py install

This time I got the following error

> > > from arango import create
> > > No handlers could be found for logger "arango.client"
> > > create
> > > function create at 0x1e24758>

However, the create method did execute.

Thanks for your help.

**Comment by appscluster** [comment] 2014-04-15 11:41
After checking further had to remove nose and mock
pip uninstall nose
pip uninstall mock
pip uninstall arango
then reinstalled arango from master zip
sudo python setup.py install

All issues resolved. Thank you for your time to help resolve this. Much appreciated.

**Comment by fceller** [comment] 2014-04-15 11:42
Thanks for testing. Let me know if you encounter any further problems.

**Closed as completed by fceller** 2014-04-15 11:42 UTC
